- name: Deploy Wine Manager Docker Container
  hosts: local
  connection: local
  become: true

  tasks:
    - name: Stop running container (if exists)
      shell: |
        docker rm -f wine-app || true

    - name: Remove existing image (if exists)
      shell: |
        docker rmi -f wine-manager:latest || true

    - name: Copy JAR file to target build directory (already done by Jenkins)
      copy:
        src: /Users/swati/.jenkins/workspace/CICD-WineApp/target/wine-manager.jar
        dest: /Users/swati/deploy/wine-manager/wine-manager.jar
        mode: '0755'

    - name: Copy Dockerfile
      copy:
        src: /Users/swati/Desktop/Msc/Second_Semester/Microservices/wine-app/Dockerfile
        dest: /Users/swati/deploy/Dockerfile

    - name: Build Docker Image
      shell: |
        export PATH=$PATH:/usr/local/bin
        docker build -t wine-manager:latest .
      args:
        chdir: /Users/swati/deploy

    - name: Run Docker Container
      shell: |
        docker run -d -p 8081:8081 --name wine-app wine-manager:latest